# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EqualizerApp(object):
    def setupUi(self, EqualizerApp):
        EqualizerApp.setObjectName("EqualizerApp")
        EqualizerApp.resize(1145, 969)
        EqualizerApp.setStyleSheet("background : rgb(179, 179, 179)\n"
"")
        self.centralwidget = QtWidgets.QWidget(EqualizerApp)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setStyleSheet("color: white;\n"
"background : rgb(179, 179, 179)\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(0, 40))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: black\n"
";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.load_btn = QtWidgets.QPushButton(self.groupBox)
        self.load_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.load_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.load_btn.setStyleSheet("\n"
"QPushButton {\n"
"background :rgb(0, 111, 163);\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 2px solid #475c7a; \n"
"    cursor: pointer; \n"
"\n"
"border-radius: 10px ; \n"
"color:#34455e;\n"
"}")
        self.load_btn.setObjectName("load_btn")
        self.verticalLayout.addWidget(self.load_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(0, 40))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: black\n"
";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.modes_combobox = QtWidgets.QComboBox(self.groupBox)
        self.modes_combobox.setMinimumSize(QtCore.QSize(0, 40))
        self.modes_combobox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.modes_combobox.setStyleSheet("QComboBox, QFontComboBox {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #272727;\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png); /*Adawaita icon thene*/\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid darkgray;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #dadada;\n"
"    selection-color: #272727;\n"
"    color: #272727;\n"
"    background: white;\n"
"}")
        self.modes_combobox.setObjectName("modes_combobox")
        self.modes_combobox.addItem("")
        self.modes_combobox.addItem("")
        self.modes_combobox.addItem("")
        self.modes_combobox.addItem("")
        self.verticalLayout_2.addWidget(self.modes_combobox)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: black\n"
";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: black\n"
";")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: black\n"
";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.hear_orig_btn = QtWidgets.QPushButton(self.groupBox)
        self.hear_orig_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.hear_orig_btn.setStyleSheet("")
        self.hear_orig_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/speaker-filled-audio-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hear_orig_btn.setIcon(icon)
        self.hear_orig_btn.setFlat(True)
        self.hear_orig_btn.setObjectName("hear_orig_btn")
        self.horizontalLayout.addWidget(self.hear_orig_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: black\n"
";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.hear_eq_btn = QtWidgets.QPushButton(self.groupBox)
        self.hear_eq_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.hear_eq_btn.setStyleSheet("")
        self.hear_eq_btn.setText("")
        self.hear_eq_btn.setIcon(icon)
        self.hear_eq_btn.setFlat(True)
        self.hear_eq_btn.setObjectName("hear_eq_btn")
        self.horizontalLayout_2.addWidget(self.hear_eq_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(0, 40))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: black\n"
";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.smoothing_window_combobox = QtWidgets.QComboBox(self.groupBox)
        self.smoothing_window_combobox.setMinimumSize(QtCore.QSize(0, 40))
        self.smoothing_window_combobox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.smoothing_window_combobox.setStyleSheet("QComboBox, QFontComboBox {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #272727;\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png); /*Adawaita icon thene*/\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid darkgray;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #dadada;\n"
"    selection-color: #272727;\n"
"    color: #272727;\n"
"    background: white;\n"
"}")
        self.smoothing_window_combobox.setObjectName("smoothing_window_combobox")
        self.smoothing_window_combobox.addItem("")
        self.smoothing_window_combobox.addItem("")
        self.smoothing_window_combobox.addItem("")
        self.smoothing_window_combobox.addItem("")
        self.verticalLayout_5.addWidget(self.smoothing_window_combobox)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_2.setSizeIncrement(QtCore.QSize(0, 40))
        self.lineEdit_2.setStyleSheet("color: black\n"
";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.apply_btn = QtWidgets.QPushButton(self.groupBox)
        self.apply_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.apply_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.apply_btn.setStyleSheet("\n"
"QPushButton {\n"
"background :rgb(0, 111, 163);\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 2px solid #475c7a; \n"
"    cursor: pointer; \n"
"\n"
"border-radius: 10px ; \n"
"color:#34455e;\n"
"}")
        self.apply_btn.setObjectName("apply_btn")
        self.verticalLayout_5.addWidget(self.apply_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black\n"
";")
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.original_graph = PlotWidget(self.centralwidget)
        self.original_graph.setMinimumSize(QtCore.QSize(0, 230))
        self.original_graph.setMaximumSize(QtCore.QSize(16777215, 230))
        self.original_graph.setStyleSheet("background: white")
        self.original_graph.setObjectName("original_graph")
        self.verticalLayout_7.addWidget(self.original_graph)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.play_pause_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_pause_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.play_pause_btn.setStyleSheet("")
        self.play_pause_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause_btn.setIcon(icon1)
        self.play_pause_btn.setFlat(True)
        self.play_pause_btn.setObjectName("play_pause_btn")
        self.horizontalLayout_3.addWidget(self.play_pause_btn)
        self.replay_btn = QtWidgets.QPushButton(self.centralwidget)
        self.replay_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.replay_btn.setStyleSheet("")
        self.replay_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imgs/replay.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.replay_btn.setIcon(icon2)
        self.replay_btn.setFlat(True)
        self.replay_btn.setObjectName("replay_btn")
        self.horizontalLayout_3.addWidget(self.replay_btn)
        self.zoom_in_btn = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_in_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.zoom_in_btn.setStyleSheet("")
        self.zoom_in_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imgs/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in_btn.setIcon(icon3)
        self.zoom_in_btn.setFlat(True)
        self.zoom_in_btn.setObjectName("zoom_in_btn")
        self.horizontalLayout_3.addWidget(self.zoom_in_btn)
        self.zoom_out_btn = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_out_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.zoom_out_btn.setStyleSheet("")
        self.zoom_out_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imgs/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out_btn.setIcon(icon4)
        self.zoom_out_btn.setFlat(True)
        self.zoom_out_btn.setObjectName("zoom_out_btn")
        self.horizontalLayout_3.addWidget(self.zoom_out_btn)
        self.speed_up_btn = QtWidgets.QPushButton(self.centralwidget)
        self.speed_up_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.speed_up_btn.setStyleSheet("")
        self.speed_up_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("imgs/speed up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.speed_up_btn.setIcon(icon5)
        self.speed_up_btn.setFlat(True)
        self.speed_up_btn.setObjectName("speed_up_btn")
        self.horizontalLayout_3.addWidget(self.speed_up_btn)
        self.speed_down_btn = QtWidgets.QPushButton(self.centralwidget)
        self.speed_down_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.speed_down_btn.setStyleSheet("")
        self.speed_down_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("imgs/speed down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.speed_down_btn.setIcon(icon6)
        self.speed_down_btn.setFlat(True)
        self.speed_down_btn.setObjectName("speed_down_btn")
        self.horizontalLayout_3.addWidget(self.speed_down_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: black\n"
";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.specto_frame_before = QtWidgets.QFrame(self.centralwidget)
        self.specto_frame_before.setMinimumSize(QtCore.QSize(430, 0))
        self.specto_frame_before.setMaximumSize(QtCore.QSize(430, 16777215))
        self.specto_frame_before.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.specto_frame_before.setFrameShadow(QtWidgets.QFrame.Raised)
        self.specto_frame_before.setObjectName("specto_frame_before")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.specto_frame_before)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.spectrogram_before = QtWidgets.QVBoxLayout()
        self.spectrogram_before.setObjectName("spectrogram_before")
        self.verticalLayout_16.addLayout(self.spectrogram_before)
        self.verticalLayout_8.addWidget(self.specto_frame_before)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: black\n"
";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.equalized_graph = PlotWidget(self.centralwidget)
        self.equalized_graph.setMinimumSize(QtCore.QSize(0, 230))
        self.equalized_graph.setMaximumSize(QtCore.QSize(16777215, 230))
        self.equalized_graph.setObjectName("equalized_graph")
        self.verticalLayout_9.addWidget(self.equalized_graph)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: black\n"
";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.specto_frame_after = QtWidgets.QFrame(self.centralwidget)
        self.specto_frame_after.setMinimumSize(QtCore.QSize(430, 0))
        self.specto_frame_after.setMaximumSize(QtCore.QSize(430, 16777215))
        self.specto_frame_after.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.specto_frame_after.setFrameShadow(QtWidgets.QFrame.Raised)
        self.specto_frame_after.setObjectName("specto_frame_after")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.specto_frame_after)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.spectrogram_after = QtWidgets.QVBoxLayout()
        self.spectrogram_after.setObjectName("spectrogram_after")
        self.verticalLayout_17.addLayout(self.spectrogram_after)
        self.verticalLayout_10.addWidget(self.specto_frame_after)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: black\n"
";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.frequancy_graph = PlotWidget(self.centralwidget)
        self.frequancy_graph.setMinimumSize(QtCore.QSize(0, 230))
        self.frequancy_graph.setMaximumSize(QtCore.QSize(16777215, 230))
        self.frequancy_graph.setObjectName("frequancy_graph")
        self.verticalLayout_11.addWidget(self.frequancy_graph)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.sliders_frame = QtWidgets.QFrame(self.centralwidget)
        self.sliders_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.sliders_frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.sliders_frame.setStyleSheet("QSlider::groove {\n"
"    border: 1px solid #bbbbbb;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 6px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page, QSlider::sub-page {\n"
"    border: 1px transparent;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::add-page:horizontal:disabled, QSlider::sub-page:horizontal:disabled, QSlider::add-page:vertical:disabled, QSlider::sub-page:vertical:disabled {\n"
"    background: #b9b9b9;\n"
"}")
        self.sliders_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sliders_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sliders_frame.setObjectName("sliders_frame")
        self.verticalLayout_12.addWidget(self.sliders_frame)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        EqualizerApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EqualizerApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 26))
        self.menubar.setObjectName("menubar")
        EqualizerApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EqualizerApp)
        self.statusbar.setObjectName("statusbar")
        EqualizerApp.setStatusBar(self.statusbar)

        self.retranslateUi(EqualizerApp)
        self.modes_combobox.setCurrentIndex(0)
        self.lineEdit_2.returnPressed.connect(self.apply_btn.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EqualizerApp)

    def retranslateUi(self, EqualizerApp):
        _translate = QtCore.QCoreApplication.translate
        EqualizerApp.setWindowTitle(_translate("EqualizerApp", "EqualizerApp"))
        self.groupBox.setTitle(_translate("EqualizerApp", "Controls "))
        self.label_6.setText(_translate("EqualizerApp", "  Browse"))
        self.load_btn.setText(_translate("EqualizerApp", "Load"))
        self.label_5.setText(_translate("EqualizerApp", " Modes "))
        self.modes_combobox.setItemText(0, _translate("EqualizerApp", "Uniform Range"))
        self.modes_combobox.setItemText(1, _translate("EqualizerApp", "Musical Instruments"))
        self.modes_combobox.setItemText(2, _translate("EqualizerApp", "Animal Sounds"))
        self.modes_combobox.setItemText(3, _translate("EqualizerApp", "ECG Abnormalities"))
        self.label_10.setText(_translate("EqualizerApp", " Spectrogram "))
        self.checkBox.setText(_translate("EqualizerApp", "Show/Hide"))
        self.label_9.setText(_translate("EqualizerApp", "Audio Before"))
        self.label_11.setText(_translate("EqualizerApp", "Audio After"))
        self.label_7.setText(_translate("EqualizerApp", "Smoothing Window"))
        self.smoothing_window_combobox.setItemText(0, _translate("EqualizerApp", "Rectangular"))
        self.smoothing_window_combobox.setItemText(1, _translate("EqualizerApp", "Hamming"))
        self.smoothing_window_combobox.setItemText(2, _translate("EqualizerApp", "Hanning"))
        self.smoothing_window_combobox.setItemText(3, _translate("EqualizerApp", "Gaussian"))
        self.lineEdit_2.setPlaceholderText(_translate("EqualizerApp", "Enter Std Value"))
        self.apply_btn.setText(_translate("EqualizerApp", "Apply"))
        self.label.setText(_translate("EqualizerApp", "Original plot    "))
        self.label_3.setText(_translate("EqualizerApp", "Original Spectrogram"))
        self.label_2.setText(_translate("EqualizerApp", "Equalized  plot "))
        self.label_4.setText(_translate("EqualizerApp", "Equalized Spectrogram"))
        self.label_8.setText(_translate("EqualizerApp", "Frequancy domain"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EqualizerApp = QtWidgets.QMainWindow()
    ui = Ui_EqualizerApp()
    ui.setupUi(EqualizerApp)
    EqualizerApp.show()
    sys.exit(app.exec_())
